#!/bin/bash

# This script finds all children of specified interface name.
# It will print out a list of all ifaces that are not DISABLED
# and have $1 in its REQUIRES option.
# TODO: handle 'boot' arg?

usage()
{
	echo "Usage: $0 <interface>" >> /dev/stderr
	exit 1
}

[ -z "$1" ] && usage
PARENTNAME=$1
CHILDREN=""
. $SCRIPTDIR/functions
export MYIFACEDIR NAME

# same code as in etcnet.init
for IFACEPATH in $IFACEDIR/*; do
	NAME=${IFACEPATH//*\//}
	[ "$NAME" = "default" -o "$NAME" = "CVS" ] && continue
	MYIFACEDIR=$IFACEDIR/$NAME
	unset DISABLED
	pickup_options
	is_yes "$DISABLED" && continue
	[ "$REQUIRES" = "$PARENTNAME" ] && CHILDREN="$CHILDREN $NAME"
done

echo $CHILDREN
