#!/bin/sh

. $SCRIPTDIR/functions

$MODPROBE ipv6

xargise_file $MYIFACEDIR/ipv6address "$IP -6 address add dev $NAME"
iface_is_up $NAME && \
xargise_file $MYIFACEDIR/ipv6route "$IP -6 route append dev $NAME"
