#!/bin/bash

usage()
{
	echo '/etc/net QoS handler'
	echo "Usage: $0 <interface> <start|stop>" >&2
	exit 1
}

[ -d $MYIFACEDIR/qos/ -a -x $MYIFACEDIR/qos/ ] || exit 0
[ $# -ge 2 ] || usage
NAME=$1
ACTION=$2
eval "IPV4ADDRESS=($3)"
eval "IPV6ADDRESS=($4)"
pickup_defaults
pickup_options

case $ACTION in
	start)
		# process_qos_dir <current dir> <parent> [last qdisc handle] [extra]
		process_qos_dir()
		{
			local NODENAME NODETYPE NODEIDPREFIX NODEATTRS NODEID
			local NODEDIR=${1:?missing 1st arg to $FUNCNAME}
			local NODENAME=${NODEDIR//*\//}
			# this arg is 'root' for the first call and 'parent x:y' for the rest
			local PARENTNODE=${2:?missing 2nd arg to $FUNCNAME}
			local LAST_QDISC_HANDLE=$3
			local EXTRAATTRS=$4
			local CANDCLASS=`profiled_filename $NODEDIR/class`
			local CANDQDISC=`profiled_filename $NODEDIR/qdisc`
			local RECLEVEL
			if [ -f $CANDCLASS ]; then
				NODETYPE=class
				NODEIDPREFIX=classid
				NODEID="$LAST_QDISC_HANDLE$NODENAME"
				NODEATTRS="`head -1 $CANDCLASS`"
			elif [ -f $CANDQDISC ]; then
				NODETYPE=qdisc
				NODEIDPREFIX=handle
				NODEID="$NODENAME:"
				LAST_QDISC_HANDLE=$NODEID
				NODEATTRS=`head -1 $CANDQDISC`
			else
				print_error "Unknown node type in $FUNCNAME, RECLEVEL=$RECLEVEL, CWD=$NODEDIR"
				return 1
			fi
			$TC $NODETYPE add dev $NAME $PARENTNODE $NODEIDPREFIX $NODEID $EXTRAATTRS $NODEATTRS
		# setup filters
			local CANDFILTER=`profiled_filename $NODEDIR/filter`
			local CANDEXTRAFILTER=`profiled_filename $NODEDIR/extra.filter`
			if [ $NODETYPE = class -a -s $CANDFILTER ]; then
				$DENOISE $CANDFILTER | while read FILTEREXPR; do
					$TC filter add dev $NAME $PARENTNODE `head -1 $CANDEXTRAFILTER 2>/dev/null` $FILTEREXPR flowid $NODEID
				done
			fi
			RECLEVEL=$((RECLEVEL+1))
			local CANDEXTRA=`profiled_filename $NODEDIR/extra`
			local cdir
			for cdir in $NODEDIR/*; do
				# Take base name of each directory and build up the best match
				# for current profile and host. If the full name and the best
				# match are equal, go on.
				[ -d $cdir ] || continue
				local base=${cdir%#*}
				base=${base%@*}
				local bestmatch=`profiled_filename $base`
				[ "$bestmatch" = "$cdir" ] || continue
				$FUNCNAME `profiled_filename $cdir` "parent $NODEID" "$LAST_QDISC_HANDLE" "`head -1 $CANDEXTRA 2>/dev/null`"
			done
			RECLEVEL=$((RECLEVEL-1))
			return 0
		}
		# clean up
		$TC qdisc del dev $NAME root >/dev/null 2>&1

		# do the rest
		cd $MYIFACEDIR/qos/
		export RECLEVEL=0
		# process only the first dir
		for d in $MYIFACEDIR/qos/*; do
			[ -d $d ] && {
				process_qos_dir $d root && print_progress
				break
			}
		done
	;;
	stop)
		$TC qdisc del dev $NAME root >/dev/null 2>&1
	;;
	*)
		print_error "Illegal argument to $0: '$ACTION'"
	;;
esac
