#!/bin/bash

pickup_defaults
$MODPROBE ipv6

xargise_file $MYIFACEDIR/ipv6address "$IP -6 address add dev $NAME"
if iface_is_up $NAME; then
	# setup routes
	local SRCFILE=`profiled_filename $MYIFACEDIR/ipv6route`
	[ -s "$SRCFILE" ] && $DENOISE "$SRCFILE" | \
	while read FIRST REST; do
	# If there is no operation, substitute default, otherwise keep.
		case "$FIRST" in
			add|del|change|append|replace)
				$IP -6 route $FIRST $REST
			;;
			*)
				$IP -6 route append $FIRST $REST
			;;
		esac
		print_progress
	done
fi
