#!/bin/bash

# IPX protocol configuration script, works like brctl processor.

pickup_options

IPX_INTF_FILE=`profiled_filename $MYIFACEDIR/ipxinterface`
[ -s "$IPX_INTF_FILE" ] || exit 0
[ -x "$IPX_INTERFACE" ] || {
	print_error "$IPX_INTERFACE does not exist or is not executable. Try installing ipxutils RPM."
	return 1
}
[ -f /proc/net/ipx ] || $MODPROBE ipx

$DENOISE $IPX_INTF_FILE | sed "s/AUTO /$NAME /" | \
xargs --max-lines=1 $IPX_INTERFACE add && print_progress
