#!/bin/bash

# This script handles firewall configuration for given iface name.

usage()
{
	echo '/etc/net FireWall handler'
	echo "Usage: $0 <interface> <action>" >&2
	exit 1
}


[ -z "$1" -o -z "$2" ] && usage

NAME=$1
ACTION=$2
eval "IPV4ADDRESS=($3)"
eval "IPV6ADDRESS=($4)"

pickup_defaults
. ${SCRIPTDIR:=/etc/net/scripts}/functions-fw

[ -z "$NETPROFILE" ] && init_netprofile

if [ -d $IFACEDIR/$NAME@$NETHOST ]; then
    MYIFACEDIR=$IFACEDIR/$NAME@$NETHOST
else
    MYIFACEDIR=$IFACEDIR/$NAME
fi

[ -d "$MYIFACEDIR" ] || {
    print_error "interface configuration directory $MYIFACEDIR not found"
    exit 1
}

[ -z "$CONFIG_FW" ] && \
    {
	SourceIfNotEmpty `profiled_filename /etc/net/ifaces/default/options`
	SourceIfNotEmpty `profiled_filename /etc/net/ifaces/default/fw/options`
    }

if  ! is_yes "$CONFIG_FW";  then
    print_message "Firewall is disabled"
    exit 1
fi

SourceIfNotEmpty "$MYIFACEDIR/fw/options"

# FIXME
#init_netprofile
#pickup_options

for CFW_TYPE in $FW_TYPE; do
    case "$CFW_TYPE" in
        "iptables")
		    # FIXME Does iptables support only IPv4?
		    is_yes "$CONFIG_IPV4" || continue
		    [ -d "$MYIFACEDIR/fw/$CFW_TYPE" ] || continue
		    # Load own interface syntax if exists
		    [ "$NAME" != "default" ] && is_yes "$IPTABLES_HUMAN_SYNTAX" && \
			{
			    [ -f "$MYIFACEDIR/fw/$CFW_TYPE/syntax" ] && [ -s "$MYIFACEDIR/fw/$CFW_TYPE/syntax" ] && \
				{
				    IPTABLES_SYNTAX_DIR="$MYIFACEDIR/fw/$CFW_TYPE"
				    IPTABLES_SYNTAX=
				    IPTABLES_SED_RULES=
				}
			}
		    case "$ACTION" in
			start)
				iptables_preload
				iptables_start "$NAME"
				;;
			stop)
				iptables_preload
				iptables_stop "$NAME"
				;;
			restart)
				iptables_preload
				iptables_stop "$NAME"
				iptables_start "$NAME"
				;;
			reload)
				iptables_preload
				iptables_stop "$NAME"
				iptables_start "$NAME"
				;;
			*)
				echo "${0##*/} {start|stop|restart|reload}"
				exit 1
				;;
		    esac
		    ;;
        "ip6tables")
		    # FIXME Does ip6tables support only IPv6?
		    is_yes "$CONFIG_IPV6" || continue
		    [ -d "$MYIFACEDIR/fw/$CFW_TYPE" ] || continue
		    # Load own interface syntax if exists
		    [ "$NAME" != "default" ] && is_yes "$IP6TABLES_HUMAN_SYNTAX" && \
			{
			    [ -f "$MYIFACEDIR/fw/$CFW_TYPE/syntax" ] && [ -s "$MYIFACEDIR/fw/$CFW_TYPE/syntax" ] && \
				{
				    IP6TABLES_SYNTAX_DIR="$MYIFACEDIR/fw/$CFW_TYPE"
				    IP6TABLES_SYNTAX=
				    IP6TABLES_SED_RULES=
				}
			}
		    case "$ACTION" in
			start)
				ip6tables_preload
				ip6tables_start "$NAME"
				;;
			stop)
				ip6tables_preload
				ip6tables_stop "$NAME"
				;;
			restart)
				ip6tables_preload
				ip6tables_stop "$NAME"
				ip6tables_start "$NAME"
				;;
			reload)
				ip6tables_preload
				ip6tables_stop "$NAME"
				ip6tables_start "$NAME"
				;;
			*)
				echo "${0##*/} {start|stop|restart|reload}"
				exit 1
				;;
		    esac
		    ;;
	"ebtables")
		    [ -d "$MYIFACEDIR/fw/$CFW_TYPE" ] || continue
		    case "$ACTION" in
		        start)
			        ebtables_start "$NAME"
			        ;;
			stop)
				ebtables_stop "$NAME"
				;;
			restart)
				ebtables_stop "$NAME"
				ebtables_start "$NAME"
				;;
			reload)
				ebtables_stop "$NAME"
				ebtables_start "$NAME"
				;;
			*)
				echo "${0##*/} {start|stop|restart|reload}"
				exit 1
				;;
		    esac
		    ;;
		
	*)
		    echo "Firewall type $CFW_TYPE isn't supported"
    esac
done
