#!/bin/bash

# This script handles wireless extensions.

usage()
{
	echo "Usage: $0 <interface>" >&2
	exit 1
}

[ -z "$1" ] && usage
NAME=$1

pickup_defaults
pickup_options

# Dunno if $IFACEDIR/default/{iwpriv,iwconfig} can be of any use

# configure private extensions
if [ -x "${IWPRIV:=$DEFAULT_IWPRIV}" ]; then
	xargise_file $IFACEDIR/default/iwpriv "$IWPRIV $NAME"
	xargise_file $MYIFACEDIR/iwpriv "$IWPRIV $NAME"
fi

# configure WEP
if [ -x "${IWCONFIG:=$DEFAULT_IWCONFIG}" ]; then
	xargise_file $IFACEDIR/default/iwconfig "$IWCONFIG $NAME"
	xargise_file $MYIFACEDIR/iwconfig "$IWCONFIG $NAME"
fi

# configure WPA
if profiled_filename prof_conf "$MYIFACEDIR/wpa_supplicant.conf"; then
	if [ -x "${WPA_SUPPLICANT:=$DEFAULT_WPA_SUPPLICANT}" -a -x "${WPA_CLI:=$DEFAULT_WPA_CLI}" ]; then
		$WPA_SUPPLICANT -i$NAME${WPA_DRIVER:+ -D$WPA_DRIVER} \
			-B -P/var/run/wpa_supplicant-$NAME.pid -c $prof_conf && \
		$WPA_CLI -i$NAME -B -P/var/run/wpa_cli-$NAME.pid -a $SCRIPTDIR/wpa_cli.action
	else
			exit 2		# continue without wpa_cli
	fi
fi
