#!/bin/bash

. /etc/init.d/functions
SourceIfNotEmpty $SCRIPTDIR/functions

[ -s $MYIFACEDIR/ipv4address ] && cat $MYIFACEDIR/ipv4address | \
xargs --max-lines=1 $IP -4 address add dev $NAME

iface_is_up $NAME && [ -s $MYIFACEDIR/ipv4route ] && \
cat $MYIFACEDIR/ipv4route | xargs --max-lines=1 $IP -4 route append dev $NAME
