#!/bin/bash

# This script handles wireless extensions.

usage()
{
	echo "Usage: $0 <interface>" > /dev/stderr
	exit 1
}

[ -z "$1" ] && usage
NAME=$1

. $SCRIPTDIR/functions
pickup_options

# configure WEP
if [ -x "${IWCONFIG:=$DEFAULT_IWCONFIG}" ]; then
	# Dunno if $IFACEDIR/default/iwconfig can be of any use
	xargise_file $IFACEDIR/default/iwconfig "$IWCONFIG $NAME"
	xargise_file $MYIFACEDIR/iwconfig "$IWCONFIG $NAME"
fi

#configure WPA
if [ -x "${WPA_SUPPLICANT:=$DEFAULT_WPA_SUPPLICANT}" ]; then
	prof_conf=`profiled_filename $MYIFACEDIR/wpa_supplicant.conf`
	$WPA_SUPPLICANT -B -i$NAME${WPA_DRIVER:+ -D$WPA_DRIVER}${prof_conf:+ -c $prof_conf}
fi
