#!/bin/bash

pickup_defaults
pickup_options

[ -f /sys/class/net/bonding_masters ] || modprobe_with_rename bonding max_bonds=0

printf '%s%s' + "$NAME" > /sys/class/net/bonding_masters

cd /sys/class/net/$NAME/bonding

printf '%s' ${BONDMODE:-$DEFAULT_BONDMODE} > mode

eval "$BONDOPTIONS"
for VAR in *; do
	[ "$VAR" = "primary" ] && continue
	[ -n "${!VAR}" ] && printf '%s\n' "${!VAR}" > "$VAR"
done

$IP link set dev $NAME up
