#!/bin/bash

pickup_defaults
pickup_options

ensure_tuntap_node() {
	local i=5

	[ -c /dev/net/tun ] && return 0
	$MODPROBE tun || return 1
	while [ $i -gt 0 ] ; do
		[ -c /dev/net/tun ] && break
		i=$(($i - 1))
		usleep 30000
	done
	[ -c /dev/net/tun ]
}

[ -x "${TUNCTL:=$DEFAULT_TUNCTL}" ] || {
	print_error "$TUNCTL does not exist or is not executable. Try installing tunctl RPM."
	exit 1
}

ensure_tuntap_node || {
	print_error "tuntap control node does not exist"
	exit 1
}

$TUNCTL -t "$NAME" ${TUNTAP_USER:+-u $TUNTAP_USER} > /dev/null
