#!/bin/bash

pickup_defaults
pickup_options


[ -x "${TUNCTL:=$DEFAULT_TUNCTL}" ] || {
	print_error "$TUNCTL does not exist or is not executable. Try installing tunctl RPM."
	exit 1
}

modprobe_tuntap || {
	print_error "tuntap control node does not exist"
	exit 1
}

$TUNCTL -t "$NAME" ${TUNTAP_USER:+-u $TUNTAP_USER} > /dev/null
