#!/bin/bash

pickup_defaults
pickup_options

[ -x "${BRCTL:=$DEFAULT_BRCTL}" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

$BRCTL addbr $NAME
