#!/bin/bash

pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
		$MODPROBE dvb-core dvb_shutdown_timeout=0
		[ "$DVBTYPE" = "ss223" ] && $MODPROBE mt312
		[ "$DVBTYPE" = "ss226" ] && $MODPROBE stv0299
		$MODPROBE skystar2
		[ -x "${DVBNET:=$DEFAULT_DVBNET}" ] || {
			print_error "$DVBNET does not exist or is not executable for $NAME"
			exit 1
		}
		$DVBNET -p $PID
	;;
	pentanet)
		$MODPROBE pentanet
	;;
	pentaval)
		$MODPROBE scanval
		$MODPROBE pentaval
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
