#!/bin/bash

. /etc/init.d/functions
SourceIfNotEmpty $SCRIPTDIR/functions
init_profile
pickup_options

REQUIRES=${REQUIRES:?REQUIRES is missing for $NAME}
VID=${VID:?VID is missing for $NAME}

if iface_is_up $REQUIRES; then
	setup_vlan_iface $REQUIRES $VID $NAME
else
	print_error "parent interface '$REQUIRES' for '$NAME' is down"
	exit 1
fi

exit 0
