#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

# If an administrator wishes to rely on modules.conf, let's agree.
if [ -n "$MODULE" ]; then
	$MODPROBE $MODULE
else
	$IP link set dev $NAME down
fi
