#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
		$MODPROBE dvb-core dvb_shutdown_timeout=0
		[ "$DVBTYPE" = "ss223" ] && $MODPROBE mt312
		[ "$DVBTYPE" = "ss226" ] && $MODPROBE stv0299
		$MODPROBE skystar2
	;;
	pentanet)
		$MODPROBE pentanet
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
