#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

BRCTL=${BRCTL:=$DEFAULT_BRCTL}
[ -x "$BRCTL" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

$BRCTL addbr $NAME
