#!/bin/bash

. /etc/init.d/functions
SourceIfNotEmpty $SCRIPTDIR/functions
pickup_options

# If an administrator wishes to rely on modules.conf, let's agree.
MODULE=${MODULE:=$NAME}

$MODPROBE $MODULE
