#!/bin/bash

pickup_defaults
pickup_options

PROF_POSTSTOP=`profiled_filename ${OVPNPOSTSTOP:-$DEFAULT_OVPNPOSTSTOP}`

kill `cat /var/run/openvpn/$NAME.pid`

[ -x "$MYIFACEDIR/$PROF_POSTSTOP" ] && "$MYIFACEDIR/$PROF_POSTSTOP"

try_rmmod tun

is_yes "$RESTORE_DEFAULTROUTE" && [ -s /var/run/openvpn/$NAME.defaultroute ] && {
	xargise_file /var/run/openvpn/$NAME.defaultroute "$IP ro ad"
	rm -f /var/run/openvpn/$NAME.defaultroute
}

exit 0
