#!/bin/bash

pickup_defaults
pickup_options

kill `cat $OVPNRUNDIR/$NAME.pid`

try_rmmod tun

is_yes "$RESTORE_DEFAULTROUTE" && [ -s $OVPNRUNDIR/$NAME.defaultroute ] && {
	xargise_file $OVPNRUNDIR/$NAME.defaultroute "$IP ro ad"
	rm -f $OVPNRUNDIR/$NAME.defaultroute
}

sleep 3
exit 0
