#!/bin/bash

. /etc/init.d/functions
SourceIfNotEmpty $SCRIPTDIR/functions
init_profile
pickup_options

PHYSLOCAL=${PHYSLOCAL:?missing PHYSLOCAL}
PHYSREMOTE=${PHYSREMOTE:?missing PHYSREMOTE}
SPI=${SPI:?missing SPI}
IPSECADM=${IPSECADM:=$DEFAULT_IPSECADM}

$IPSECADM tunnel del $NAME
$IPSECADM sa del --src=$PHYSLOCAL --dst=$PHYSREMOTE --spi=$SPI --duplex

try_rmmod ipsec_tunnel
