#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
		# we don't rmmod skystar2 module to keep our kernel running
	;;
	pentanet)
		try_rmmod pentanet
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
