#!/bin/bash

get_ipv6_addresses()
{
    local NAME=${1:?missing 1st argument to $FUNCNAME}
    printf "$(ip addr show dev $NAME 2>/dev/null|grep  -ose "\binet\b.*\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)"|cut -f2 -d" "|cut -f1 -d"/")"
}

declare -ax IPV6ADDRESS

