#!/bin/bash

# This script is a hook for hotplug or pcmcia-cs.

usage()
{
	echo "Usage: $0 <device>"
	exit 1
}

# Look if iface name will change after ifrename call.
# Then load correct options. If hotplug/pcmcia is not
# allowed for the interface, just return. Otherwise
# rename the interface and run common iface init stuff.

[ -z "$1" ] && usage
NAME=$1
OLD_NAME=$NAME
CALLER=${2:?$0: missing 2nd arg}

case "$CALLER" in
	pcmcia_cs|hotplug)
	;;
	*)
		print_error "invalid 2nd arg to $0: '$CALLER'"
	;;
esac

. /etc/init.d/functions
SCRIPTDIR=/etc/net/scripts
SourceIfNotEmpty $SCRIPTDIR/functions

# Deal with ifrename and mappings before we try to read options,
# because iface name may change.
# Note: when called from hotplug, $1 holds correct ifname.
# In pcmcia_cs case we get the old ifname (before ifrename call).

MAPPED_NAME=`get_mapped_ifname $NAME`
if [ -n "$MAPPED_NAME" -a "$NAME" != "$MAPPED_NAME" ]; then
	NAME=$MAPPED_NAME
	echo -n '.'
fi

MYIFACEDIR=$IFACEDIR/$NAME
export IFACEDIR MYIFACEDIR SCRIPTDIR NAME

init_profile
pickup_options

is_yes "$DISABLED" && {
	echo -n 'skipped, disabled '
  exit 1
}

if [ "$CALLER" = "pcmcia_cs" ]; then
	! is_yes "$USE_PCMCIA" && {
		print_error "USE_PCMCIA is disabled for $NAME"
		exit 1
	}
fi

if [ "$CALLER" = "hotplug" ]; then
	! is_yes "$USE_HOTPLUG" && {
		print_error "USE_HOTPLUG is disabled for $NAME"
		exit 1
	}
fi

# common part
if iface_is_up $NAME; then
	ExecIfExecutable $SCRIPTDIR/ifdown-pre-local $NAME
	$IP link set dev $NAME down
	ExecIfExecutable $SCRIPTDIR/ifdown-post-local $NAME
fi

