#!/bin/bash

# This script should be called when ppp link goes down, the most
# natural way to do it is to have a hook in /etc/ppp/ip-down.d
# directory. This scripts is not intended to be run directly,
# one should use ifdown to shutdown a ppp link.

usage()
{
	echo "Usage: $0 <interface>" > /dev/stderr
	exit 1
}

[ -z "$1" ] && usage
NAME=$1
SCRIPTDIR=/etc/net/scripts
. $SCRIPTDIR/functions
MYIFACEDIR=$IFACEDIR/$NAME
export IFACEDIR MYIFACEDIR SCRIPTDIR NAME SEEN_IFACES

init_profile
pickup_options
seen_iface $NAME && exit 0
add_seen_iface $NAME

# common part
ifdown_children
if iface_is_up $NAME; then
	ExecIfExecutable $SCRIPTDIR/ifdown-pre-local $NAME
	$IP link set dev $NAME down
	ExecIfExecutable $SCRIPTDIR/ifdown-post-local $NAME
fi
