#!/bin/bash

# This script performs configuration on iface prepared
# by ifup or ifup-removable. We assume that all checks
# are done yet and the only thing remaining to be done
# is to configure the iface.

usage()
{
	echo "Usage: $0 <interface>" > /dev/stderr
	exit 1
}

[ -z "$1" ] && usage
NAME=$1

SCRIPTDIR=/etc/net/scripts
. $SCRIPTDIR/functions
MYIFACEDIR=$IFACEDIR/$NAME
export IFACEDIR MYIFACEDIR SCRIPTDIR NAME PROFILE SEEN_IFACES

init_profile
pickup_options

! is_yes "$IN_IFPLUGD" && {
	# 2. handle wireless extensions
	is_yes "$CONFIG_WIRELESS" && ExecIfExecutable $SCRIPTDIR/config-wireless $NAME && print_message -n '.'
	# 3. setup link-level params
	# useless until default prefixes are implemented
	[ -s `profiled_filename $IFACEDIR/sysctl.conf` ] && sysctl -p `profiled_filename $IFACEDIR/sysctl.conf` && print_message -n '.'
	[ -s `profiled_filename $IFACEDIR/sysctl.conf-$TYPE` ] && sysctl -p `profiled_filename $IFACEDIR/sysctl.conf-$TYPE` && print_message -n '.'
	[ -s `profiled_filename $MYIFACEDIR/sysctl.conf` ] && sysctl -p `profiled_filename $MYIFACEDIR/sysctl.conf` && print_message -n '.'
	xargise_file $IFACEDIR/default/iplink "$IP link set dev $NAME"
	xargise_file $IFACEDIR/default/iplink-$TYPE "$IP link set dev $NAME"
	xargise_file $MYIFACEDIR/iplink "$IP link set dev $NAME"
}

is_yes "$USE_IFPLUGD" && ! is_yes "$IN_IFPLUGD" && exit 0
# --- Up to this line is enough for ifplugd to run at first stage.

# 5. bring iface up
if ! is_yes $KEEP_DOWN; then
	ExecIfExecutable $SCRIPTDIR/ifup-pre-local $NAME && print_message -n '.'
	$IP link set dev $NAME up && print_message -n '.'
	if [ -x `profiled_filename $MYIFACEDIR/resolv.conf` ]; then
		rm -f /etc/resolv.conf
		ln -s `profiled_filename $MYIFACEDIR/resolv.conf` /etc/resolv.conf
		print_message -n '.'
	fi
fi

# 6. setup addresses and (only if iface is up) routes
# don't flush IPv6 auto-generated link-level addresses
is_yes $DONT_FLUSH || {
	$IP -4 address flush dev $NAME >/dev/null 2>&1
	$IP -6 address flush dev $NAME scope host >/dev/null 2>&1
	$IP -6 address flush dev $NAME scope site >/dev/null 2>&1
	$IP -6 address flush dev $NAME scope global >/dev/null 2>&1
	print_message -n '.'
}
is_yes "$CONFIG_IPV4" && ExecIfExecutable $SCRIPTDIR/config-ipv4 $NAME && print_message -n '.'
is_yes "$CONFIG_IPV6" && ExecIfExecutable $SCRIPTDIR/config-ipv6 $NAME && print_message -n '.'
is_yes "$CONFIG_IPX" &&  ExecIfExecutable $SCRIPTDIR/config-ipx $NAME  && print_message -n '.'
is_yes "$CONFIG_QOS" &&  ExecIfExecutable $SCRIPTDIR/config-qos $NAME  && print_message -n '.'

# 7. type-specific additional optional configuration
ExecIfExecutable $SCRIPTDIR/setup-$TYPE $NAME && print_message -n '.'

# 8. ifup-post
iface_is_up $NAME && ExecIfExecutable $SCRIPTDIR/ifup-post-local $NAME && print_message -n '.'

# 9. process deps
if is_yes "$IFUP_CHILDREN"; then
	IN_IFPLUGD=
	ifup_children || {
		print_error "Could not ifup children for parent iface '$NAME'"
		exit 1
	}
fi

exit 0
