#!/bin/bash

# This script is intended to be run from command-line or etcnet
# initscript. It determines if the iface should be created, then
# creates the device and calls ifup-common to do the rest.
# Removable ifaces should be controlled via hotplug and pcmcia_cs,
# which will deal with ifup-removable.

usage()
{
	echo "Usage: $0 <device>"
	exit 1
}

[ -z "$1" ] && usage
NAME=$1

. /etc/init.d/functions
SCRIPTDIR=/etc/net/scripts
SourceIfNotEmpty $SCRIPTDIR/functions
MYIFACEDIR=$IFACEDIR/$NAME
export IFACEDIR MYIFACEDIR SCRIPTDIR NAME

pickup_options

is_yes "$DISABLED" && {
	echo -n 'skipped, disabled '
  exit 1
}

if [ "$2" = "boot" -a "$ONBOOT" = "no" ]; then
	echo -n 'skipped during boot '
  exit 1
fi

# 1. check if device already exists
iface_is_up $NAME && {
	echo -n "'$NAME' skipped, already up "
	exit 1
}

# 2. make device appear

if ExecIfExecutable $SCRIPTDIR/create-$TYPE $NAME; then
	echo -n '.'
else
	echo -n '!'
	exit 1
fi

if [ -s "$IFTAB" ]; then
	[ -x $IFRENAME ] || {
		print_error "$IFRENAME is unavailable, but $IFTAB exists"
		exit 1
	}
	NEW_NAME=`$IFRENAME -c $IFTAB -i $NAME 2>/dev/null`
	if [ $? = 0 -a -n "$NEW_NAME" ]; then
		NAME=$NEW_NAME
		echo -n '.'
	fi
fi

$SCRIPTDIR/ifup-common $NAME
