#!/bin/bash

# This script is a hook for hotplug or pcmcia-cs.
# It determines if the specified iface has to be
# processed, then performs necessary pre-configuration
# and lets ifup-common do the rest.

usage()
{
	echo "Usage: $0 <interface>" > /dev/stderr
	exit 1
}

# Look if iface name will change after ifrename call.
# Then load correct options. If hotplug/pcmcia is not
# allowed for the interface, just return. Otherwise
# rename the interface and run common iface init stuff.

[ -z "$1" ] && usage
NAME=$1
OLD_NAME=$NAME
CALLER=${2:?$0: missing 2nd arg}

case "$CALLER" in
	pcmcia_cs|hotplug)
	;;
	*)
		print_error "invalid 2nd arg to $0: '$CALLER'"
		exit 1
	;;
esac

. ${SCRIPTDIR:=/etc/net/scripts}/functions

# Deal with ifrename and mappings before we try to read options,
# because iface name may change.

MAPPED_NAME=`get_mapped_ifname $NAME`
if [ -n "$MAPPED_NAME" -a "$NAME" != "$MAPPED_NAME" ]; then
	NAME=$MAPPED_NAME
	print_progress
fi

init_nethost
if [ -d $IFACEDIR/$NAME@$NETHOST ]; then
	MYIFACEDIR=$IFACEDIR/$NAME@$NETHOST
else
	MYIFACEDIR=$IFACEDIR/$NAME
fi
export IFACEDIR MYIFACEDIR SCRIPTDIR NAME NETPROFILE SEEN_IFACES

init_netprofile
pickup_options

is_yes "$DISABLED" && {
	print_message -n "skipped disabled iface $NAME"
  exit 1
}

if [ "$CALLER" = "pcmcia_cs" ]; then
	! is_yes "$USE_PCMCIA" && {
		print_error "USE_PCMCIA is disabled for $NAME"
		exit 1
	}
fi

if [ "$CALLER" = "hotplug" ]; then
	! is_yes "$USE_HOTPLUG" && {
		print_error "USE_HOTPLUG is disabled for $NAME"
		exit 1
	}
fi

[ -n "$MACADDR_WAITTIME" ] && wait_for_macaddr $NAME

# Now we know that iface should be processed. Let's go.
if [ "$NAME" != "$OLD_NAME" ]; then
	IFTAB_FILE=`profiled_filename $IFTAB`
	[ -s "$IFTAB_FILE" ] && $IFRENAME -c "$IFTAB_FILE" -i $OLD_NAME -n $NAME >/dev/null 2>&1
fi

# avoid cycles
seen_iface $NAME && exit 0
add_seen_iface $NAME

$SCRIPTDIR/ifup-common $NAME
