#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

[ -x "${SZAP:=$DEFAULT_SZAP}" ] || {
	print_error "$SZAP does not exist or is not executable for $NAME"
	exit 1
}

[ -x "${DVBNET:=$DEFAULT_DVBNET}" ] || {
	print_error "$DVBNET does not exist or is not executable for $NAME"
	exit 1
}

[-s "${CHANNELS_CONF:=$MYIFACEDIR/channels.conf}" ] || {
	print_error "empty or non-existent $CHANNELS_CONF for $NAME"
	exit 1
}

case "${SUBTYPE:?missing SUBTYPE option for $NAME, please fix}"; in
	ss223|ss226)
		${SZAP:=$DEFAULT_SZAP} -c $CHANNELS_CONF ${SZAP_ARGS:=$DEFAULT_SZAP_ARGS}
		${DVBNET:=$DEFAULT_DVBNET} -p $PID
	;;
	*)
		print_error "unknown DVB subtype '$SUBTYPE' for interface $NAME"
	;;
esac
