#!/bin/bash

. $SCRIPTDIR/functions
init_profile
pickup_options

REQUIRES=${REQUIRES:?REQUIRES must be set for $NAME}
[ -x "${BRCTL:=$DEFAULT_BRCTL}" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

for parent in $REQUIRES; do
	$BRCTL addif $NAME $parent
done

local PROF_BRCTL=`profiled_filename $MYIFACEDIR/brctl`
[ -s "$PROF_BRCTL" ] && {
	$DENOISE $PROF_BRCTL | \
	sed "s/ AUTO / $NAME /" | \
	xargs --max-lines=1 $BRCTL
} && print_progress
