#!/bin/bash

. $SCRIPTDIR/functions
init_netprofile
pickup_options

: ${HOST:?HOST must be set for $NAME}

[ -x "${IFENSLAVE:=$DEFAULT_IFENSLAVE}" ] || {
	print_error "$IFENSLAVE does not exist or is not executable. Try installing iputils RPM."
	exit 1
}

$IFENSLAVE $NAME $HOST > /dev/null
