#!/bin/bash

. $SCRIPTDIR/functions
init_profile
pickup_options

${CONFIGFILE:=`profiled_filename $MYIFACEDIR/$DEFAULT_PENTANET_CONF`}

[ -x "${PENTANETT:=$DEFAULT_PENTANETT}" ] || {
	print_error "$PENTANETT does not exist or is not executable for $NAME"
	exit 1
}

[ -s "$CONFIGFILE" ] && $PENTANETT -a -f $CONFIGFILE >/dev/null
