#!/bin/bash

ETHTOOL_OPTIONS=`profiled_filename $MYIFACEDIR/ethtool`

[ -s "$ETHTOOL_OPTIONS" ] || exit 0
if ! [ -x "${ETHTOOL:=$DEFAULT_ETHTOOL}" ]; then
	print_warning "$ETHTOOL_OPTIONS exists, but $ETHTOOL is not available!"
	# Don't return error to ifup on missing ethtool binary
	exit 0
fi

xargise_file "$ETHTOOL_OPTIONS" "$ETHTOOL -s $NAME"
