#!/bin/bash

. $SCRIPTDIR/functions
init_profile
pickup_options

[ -x "${PENTANETT:=$DEFAULT_PENTANETT}" ] || {
	print_error "$PENTANETT does not exist or is not executable for $NAME"
	exit 1
}

PROF_CONFIGFILE=`profiled_filename ${PENTANET_CONF:-$DEFAULT_PENTANET_CONF}`
[ -s "$PROF_CONFIGFILE" ] && $PENTANETT -a -f $PROF_CONFIGFILE >/dev/null
