#!/bin/bash

pickup_defaults
init_netprofile
pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
		[ -x "${SZAP:=$DEFAULT_SZAP}" ] || {
			print_error "$SZAP does not exist or is not executable for $NAME"
			exit 1
		}
		[ -s "${CHANNELS_CONF:=$MYIFACEDIR/channels.conf}" ] || {
			print_error "empty or non-existent $CHANNELS_CONF for $NAME"
			exit 1
		}
		$SZAP -c $CHANNELS_CONF ${SZAP_ARGS:=$DEFAULT_SZAP_ARGS}
	;;
	pentanet)
		[ -x "${PENTANETT:=$DEFAULT_PENTANETT}" ] || {
			print_error "$PENTANETT does not exist or is not executable for $NAME"
			exit 1
		}
		PROF_CONFIGFILE=`profiled_filename ${PENTANET_CONF:-$DEFAULT_PENTANET_CONF}`
		[ -s "$PROF_CONFIGFILE" ] && $PENTANETT -a -f $PROF_CONFIGFILE >/dev/null
	;;
	pentaval)
		[ -x "${PENTAVALT:=$DEFAULT_PENTAVALT}" ] || {
			print_error "$PENTAVALT does not exist or is not executable for $NAME"
			exit 1
		}
		PROF_CONFIGFILE=`profiled_filename ${PENTAVAL_CONF:-$DEFAULT_PENTAVAL_CONF}`
		[ -s "$PROF_CONFIGFILE" ] && $PENTAVALT -a -f $PROF_CONFIGFILE >/dev/null
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
