#!/bin/bash

pickup_defaults
init_netprofile
pickup_options

: ${HOST:?HOST must be set for $NAME}
[ -x "${BRCTL:=$DEFAULT_BRCTL}" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

for host in $HOST; do
	$BRCTL addif $NAME $host
done

PROF_BRCTL=`profiled_filename $MYIFACEDIR/brctl`
[ -s "$PROF_BRCTL" ] && {
	$DENOISE $PROF_BRCTL | $TRIM | \
	sed "s/ AUTO / $NAME /" | \
	xargs --max-lines=1 $BRCTL
} && print_progress
