#!/bin/bash

. $SCRIPTDIR/functions
init_profile
pickup_options

[ -x "${PENTANETT:=$DEFAULT_PENTANETT}" ] || {
	print_error "$PENTANETT does not exist or is not executable for $NAME"
	exit 1
}

CONFIGFILE=${CONFIGFILE:=$DEFAULT_PENTANET_CONF}
PROF_CONFIGFILE=`profiled_filename $CONFIGFILE`
[ -s "$PROF_CONFIGFILE" ] && $PENTANETT -a -f $PROF_CONFIGFILE >/dev/null
