#!/bin/bash

pickup_defaults
init_netprofile
pickup_options

: ${HOST:?HOST must be set for $NAME}
: ${BONDOPTIONS:?BONDOPTIONS must be set for $NAME}

for host in $HOST; do
	$IP link set dev $host down
	printf '%s%s' + $host > /sys/class/net/$NAME/bonding/slaves && print_progress
	# primary iface for active-backup cannot be set until enslaved
	[ "${BONDMODE:-$DEFAULT_BONDMODE}" = "active-backup" ] || continue
	echo "$BONDOPTIONS" | fgrep -qw "primary=$host" || continue
	printf '%s' $host > /sys/class/net/$NAME/bonding/primary
done
