#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
