#!/bin/bash

init_netprofile
pickup_options

: ${HOST:?HOST must be set for $NAME}
[ -x "${BRCTL:=$DEFAULT_BRCTL}" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

for host in $HOST; do
	$BRCTL delif $NAME $host
done
