#!/bin/bash

. $SCRIPTDIR/functions
pickup_options

case "${DVBTYPE:?missing DVBTYPE option for $NAME, please fix}" in
	ss223|ss226)
		[ -x "${DVBNET:=$DEFAULT_DVBNET}" ] || {
			print_error "$DVBNET does not exist or is not executable for $NAME"
			exit 1
		}
		# FIXME
		${DVBNET:=$DEFAULT_DVBNET} -d 0
	;;
	*)
		print_error "unknown DVB type '$DVBTYPE' for interface $NAME"
	;;
esac
