#!/bin/bash

. $SCRIPTDIR/functions
init_profile
pickup_options

: ${REQUIRES:?REQUIRES must be set for $NAME}
[ -x "${BRCTL:=$DEFAULT_BRCTL}" ] || {
	print_error "$BRCTL does not exist or is not executable. Try installing bridge-utils RPM."
	exit 1
}

for parent in $REQUIRES; do
	$BRCTL delif $NAME $parent
done
