#!/bin/bash

. /etc/init.d/functions
SCRIPTDIR=/etc/net/scripts
SourceIfNotEmpty $SCRIPTDIR/functions
export IFACEDIR SCRIPTDIR

$SYSCTL -p /etc/net/sysctl.conf

declare -a GROUP
GROUP[0]=''
GROUP[1]=''
GROUP[2]=''
GROUP[3]=''
GROUP[4]=''

start_group()
{
	local GROUP_ID=${1:?start_group: missing 1st arg}
	local GROUP_SIZE=`echo "${GROUP[$GROUP_ID]}" | wc -w`
#	echo "starting group $GROUP_ID ($GROUP_SIZE interfaces)"
	[ $GROUP_ID -eq 2 ] && {
		# hosted physical
		echo start_vlantab
	}
	for i in `seq 0 $((GROUP_SIZE-1))`; do
		IFNAME=`echo ${GROUP[$GROUP_ID]} | awk "{print \\$$((i+1))}"`
		echo "$SCRIPTDIR/ifup $IFNAME"
	done
}

# 1. fill in the groups

for IFACEPATH in $IFACEDIR/*; do
	NAME=${IFACEPATH//*\//}
	MYIFACEDIR=$IFACEDIR/$NAME
	export MYIFACEDIR NAME
	[ "$NAME" = "default" ] && continue
	[ "$NAME" = "CVS" ] && continue
	unset TYPE
	pickup_options
#	echo "processing $NAME of type $TYPE"
	GROUP_ID=`type2group $TYPE`
	[ -z "$GROUP_ID" ] && {
		print_error "unknown interface group for iface '$NAME' of type '$TYPE'"
		continue
	}
	GROUP[$GROUP_ID]="${GROUP[$GROUP_ID]} $NAME"
done

# 2. process each group
for i in 0 1 2 3 4; do
#	echo "group $i: ${GROUP[$i]}"
	[ -n "$GROUP[$i]" ] && start_group $i
done
