#!/bin/sh
# This script can be placed in any interface config directory. If it
# exists and is executable, it will be executed to return target
# profile name on stdout. Applicable cases to use such a script are
# for example notebooks with WiFi cards. The script could invoke iwlist
# to discover a WAP and decide which profile to use. When combined with
# removable WiFi card, this could mean that for reconfiguring interface
# for a new environment it will be enough to unplug and plug back
# the card. I could imagine some other applications for this feature.
# Original idea: Alexander Bokovoy
# (http://www.livejournal.com/users/abbra/4508.html?mode=reply)

