.TH "etcnet-options" "5" "0.8.0" "Denis Ovsienko <info@etcnet.org>" ""
.SH "NAME"

.SH "DESCRIPTION"

.SH "COMMON OPTIONS"
.IP TYPE
This option defines interface type. It is required, if interface type cannot be
found from interface name and if DISABLED is not set.
.IP ONBOOT
.IP DISABLED
.SH "FILES"
/etc/net/iftab
/etc/net/sysctl.conf
/etc/net/hosttab
/etc/net/vlantab
