.TH "etcnet-options" "5" "0.8.0" "Denis Ovsienko <info@etcnet.org>" ""
.SH "NAME"

.SH "DESCRIPTION"
/etc/net controls your network configuration. Once you have created your configuration, you should be able to control state of your host with 3 scripts: ifup, ifdown, network.init.
.SH "BUGS"

.SH "SEE ALSO"
ip, tc
.SH "FILES"
/etc/net/iftab
/etc/net/sysctl.conf
/etc/net/hosttab
/etc/net/vlantab
